cdc_setup:
	spyglass -project cdc.prj -goals "cdc/cdc_setup_check" -batch

cdc_verify:
	spyglass -project cdc.prj -goals "cdc/cdc_verify_struct" -batch

gui:
	spyglass -project cdc.prj 

clean:
	rm -rf chip_lib *.log *_results
